<a href="https://colab.research.google.com/github/renanteod/GCollab/blob/main/roteiro02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Roteiro Redes Neurais e Deep Learning**
## Utilizar este Notebook para executar os comandos.
**Arquivo de referência:** *Roteiro Redes Neurais e Deep Learning.docx*

In [22]:
import torch
import keras
import tensorflow as tf
import numpy as np
import os
import matplotlib.pyplot as plt

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input, MaxPool2D, Conv2D, GlobalMaxPool2D, Flatten, Dropout
from keras import ops, layers

from tensorflow.keras.datasets import mnist

In [23]:
model = Sequential(
    [
        Input(shape=(784,)),
        Dense(4, activation= 'relu', name='intermediária 1'),
        Dense(2)
    ]
)

In [24]:
model1 = Sequential()

In [25]:
model1.add(Dense(4, activation= 'relu'))

In [26]:
model1.add(Dense(2))

In [27]:
print(model.summary())

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ intermediária 1 (Dense)         │ (None, 4)              │         3,140 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 2)              │            10 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,150 (12.30 KB)

 Trainable params: 3,150 (12.30 KB)

 Non-trainable params: 0 (0.00 B)

None


In [28]:
print(model1.summary())

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_10 (Dense)                │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [32]:
x = ops.ones((1,784))

In [30]:
model.weights

[<Variable path=sequential_6/intermediária 1/kernel, shape=(784, 4), dtype=float32, value=[[ 0.00842614 -0.06204214  0.04567561  0.02856537]
  [ 0.07225418  0.02968212 -0.042126    0.05902837]
  [ 0.02374608  0.04836902 -0.08297221 -0.01308192]
  ...
  [ 0.04179098  0.07210165 -0.05732458  0.06594636]
  [ 0.08393878 -0.01638559 -0.06575653  0.0478297 ]
  [-0.03186012  0.0154261  -0.07569881  0.08112931]]>,
 <Variable path=sequential_6/intermediária 1/bias, shape=(4,), dtype=float32, value=[0. 0. 0. 0.]>,
 <Variable path=sequential_6/dense_9/kernel, shape=(4, 2), dtype=float32, value=[[-0.12664938 -0.8778331 ]
  [-0.47092056 -0.432662  ]
  [ 0.2085743   0.68082285]
  [-0.38103628  0.11636353]]>,
 <Variable path=sequential_6/dense_9/bias, shape=(2,), dtype=float32, value=[0. 0.]>]

In [33]:
y = model(x)
print(y)

tf.Tensor([[-0.13841553 -0.95938677]], shape=(1, 2), dtype=float32)
