<a href="https://colab.research.google.com/github/renanteod/GCollab/blob/main/roteiro02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Roteiro Redes Neurais e Deep Learning**
## Utilizar este Notebook para executar os comandos.
**Arquivo de referência:** *Roteiro Redes Neurais e Deep Learning.docx*

In [ ]:
import torch
import keras
import tensorflow as tf
import numpy as np
import os
import matplotlib.pyplot as plt

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input, MaxPool2D, Conv2D, GlobalMaxPool2D, Flatten, Dropout
from keras import ops, layers

from tensorflow.keras.datasets import mnist

In [ ]:
model = Sequential(
    [
        Input(shape=(784,)),
        Dense(4, activation= 'relu', name='intermediária 1'),
        Dense(2)
    ]
)

In [ ]:
model1 = Sequential()

In [ ]:
model1.add(Dense(4, activation= 'relu'))

In [ ]:
model1.add(Dense(2))

In [ ]:
print(model.summary())

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ intermediária 1 (Dense)         │ (None, 4)              │         3,140 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 2)              │            10 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,150 (12.30 KB)

 Trainable params: 3,150 (12.30 KB)

 Non-trainable params: 0 (0.00 B)

None


In [ ]:
print(model1.summary())

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_10 (Dense)                │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [ ]:
x = ops.ones((1,784))

In [ ]:
model.weights

[<Variable path=sequential_6/intermediária 1/kernel, shape=(784, 4), dtype=float32, value=[[ 0.00842614 -0.06204214  0.04567561  0.02856537]
  [ 0.07225418  0.02968212 -0.042126    0.05902837]
  [ 0.02374608  0.04836902 -0.08297221 -0.01308192]
  ...
  [ 0.04179098  0.07210165 -0.05732458  0.06594636]
  [ 0.08393878 -0.01638559 -0.06575653  0.0478297 ]
  [-0.03186012  0.0154261  -0.07569881  0.08112931]]>,
 <Variable path=sequential_6/intermediária 1/bias, shape=(4,), dtype=float32, value=[0. 0. 0. 0.]>,
 <Variable path=sequential_6/dense_9/kernel, shape=(4, 2), dtype=float32, value=[[-0.12664938 -0.8778331 ]
  [-0.47092056 -0.432662  ]
  [ 0.2085743   0.68082285]
  [-0.38103628  0.11636353]]>,
 <Variable path=sequential_6/dense_9/bias, shape=(2,), dtype=float32, value=[0. 0.]>]

In [ ]:
y = model(x)
print(y)

tf.Tensor([[-0.13841553 -0.95938677]], shape=(1, 2), dtype=float32)


In [1]:
import torch
import tensorflow as tf
import os
import numpy as np
import keras
from keras import layers, ops

In [32]:
inputs = keras.Input (shape=(784,), name= 'digits')
x = layers.Dense(128, activation= 'relu', name= 'intermediaria_1')(inputs)
x = layers.Dense(128, activation='relu', name= 'intermediaria_2')(x)
x = layers.Dense(64, activation='relu', name= 'intermediaria_3')(x)
x = layers.Dense(32, activation='relu', name= 'intermediaria_4')(x)
output = layers.Dense(10, activation='softmax', name= 'predictions')(x)

model = keras.Model(inputs=inputs, outputs=output)

In [33]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

In [34]:
x_train = x_train.reshape(60000, 784).astype('float32') / 255
x_test = x_test.reshape(10000, 784).astype('float32') / 255
y_train = y_train.astype('float32')
y_test = y_test.astype('float32')

x_val = x_train[-10000:]
y_val = y_train[-10000:]
x_train = x_train[:-10000]
y_train = y_train[:-10000]

In [35]:
model.compile(
	optimizer=keras.optimizers.RMSprop(),
	loss=keras.losses.SparseCategoricalCrossentropy(),
	metrics=[keras.metrics.SparseCategoricalAccuracy()],
)



In [38]:
history = model.fit(
	x_train,
	y_train,
	batch_size=64,
	epochs=8,
	validation_data=(x_val, y_val),
)


Epoch 1/8
782/782 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 0.0302 - sparse_categorical_accuracy: 0.9908 - val_loss: 0.1484 - val_sparse_categorical_accuracy: 0.9753
Epoch 2/8
782/782 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - loss: 0.0215 - sparse_categorical_accuracy: 0.9940 - val_loss: 0.1298 - val_sparse_categorical_accuracy: 0.9769
Epoch 3/8
782/782 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 0.0224 - sparse_categorical_accuracy: 0.9939 - val_loss: 0.1468 - val_sparse_categorical_accuracy: 0.9785
Epoch 4/8
782/782 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 0.0152 - sparse_categorical_accuracy: 0.9956 - val_loss: 0.1433 - val_sparse_categorical_accuracy: 0.9782
Epoch 5/8
782/782 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 0.0144 - sparse_categorical_accuracy: 0.9962 - val_loss: 0.1596 - val_sparse_categorical_accuracy: 0.9778
Epoch 6/8
782/782 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 0.0137 - sparse_categorical_accuracy: 0.9960 - val_loss: 0.1473 - val_sparse_categorical_accuracy: 0.9801
Epoch 7/8


In [37]:
print(history.history)
results = model.evaluate(x_test, y_test, batch_size=128)
predictions = model.predict(x_test[:3])
print('test loss, test acc: ', results, ' | predictions shape: ', predictions.shape)


{'loss': [0.29644420742988586, 0.12201502919197083, 0.09048145264387131, 0.07562638819217682, 0.06360454857349396, 0.05359292030334473, 0.04808257892727852, 0.043518636375665665], 'sparse_categorical_accuracy': [0.9107599854469299, 0.963919997215271, 0.9734600186347961, 0.9777200222015381, 0.9818800091743469, 0.985260009765625, 0.9872999787330627, 0.9885200262069702], 'val_loss': [0.1977066546678543, 0.1113746240735054, 0.10773269087076187, 0.0996401309967041, 0.12980292737483978, 0.10902804136276245, 0.16157886385917664, 0.1437726616859436], 'val_sparse_categorical_accuracy': [0.9398999810218811, 0.9700999855995178, 0.9711999893188477, 0.9747999906539917, 0.9692000150680542, 0.9754999876022339, 0.9704999923706055, 0.9731000065803528]}
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1696 - sparse_categorical_accuracy: 0.9687
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step
test loss, test acc:  [0.13334524631500244, 0.9760000109672546]  | predictions shape:  (3, 10)
