<a href="https://colab.research.google.com/github/renanteod/GCollab/blob/main/roteiro02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Roteiro Redes Neurais e Deep Learning**
## Utilizar este Notebook para executar os comandos.
**Arquivo de referência:** *Roteiro Redes Neurais e Deep Learning.docx*

In [ ]:
import torch
import keras
import tensorflow as tf
import numpy as np
import os
import matplotlib.pyplot as plt

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input, MaxPool2D, Conv2D, GlobalMaxPool2D, Flatten, Dropout
from keras import ops, layers

from tensorflow.keras.datasets import mnist

In [ ]:
model = Sequential(
    [
        Input(shape=(784,)),
        Dense(4, activation= 'relu', name='intermediária 1'),
        Dense(2)
    ]
)

In [ ]:
model1 = Sequential()

In [ ]:
model1.add(Dense(4, activation= 'relu'))

In [ ]:
model1.add(Dense(2))

In [ ]:
print(model.summary())

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ intermediária 1 (Dense)         │ (None, 4)              │         3,140 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 2)              │            10 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,150 (12.30 KB)

 Trainable params: 3,150 (12.30 KB)

 Non-trainable params: 0 (0.00 B)

None


In [ ]:
print(model1.summary())

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_10 (Dense)                │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [ ]:
x = ops.ones((1,784))

In [ ]:
model.weights

[<Variable path=sequential_6/intermediária 1/kernel, shape=(784, 4), dtype=float32, value=[[ 0.00842614 -0.06204214  0.04567561  0.02856537]
  [ 0.07225418  0.02968212 -0.042126    0.05902837]
  [ 0.02374608  0.04836902 -0.08297221 -0.01308192]
  ...
  [ 0.04179098  0.07210165 -0.05732458  0.06594636]
  [ 0.08393878 -0.01638559 -0.06575653  0.0478297 ]
  [-0.03186012  0.0154261  -0.07569881  0.08112931]]>,
 <Variable path=sequential_6/intermediária 1/bias, shape=(4,), dtype=float32, value=[0. 0. 0. 0.]>,
 <Variable path=sequential_6/dense_9/kernel, shape=(4, 2), dtype=float32, value=[[-0.12664938 -0.8778331 ]
  [-0.47092056 -0.432662  ]
  [ 0.2085743   0.68082285]
  [-0.38103628  0.11636353]]>,
 <Variable path=sequential_6/dense_9/bias, shape=(2,), dtype=float32, value=[0. 0.]>]

In [ ]:
y = model(x)
print(y)

tf.Tensor([[-0.13841553 -0.95938677]], shape=(1, 2), dtype=float32)


In [1]:
import torch
import tensorflow as tf
import os
import numpy as np
import keras
from keras import layers, ops

In [3]:
inputs = keras.Input (shape=(784,), name= 'digits')
x = layers.Dense(64, activation= 'relu', name= 'intermediária_1')(inputs)
x = layers.Dense(64, activation='relu', name= 'intermediária_2')(x)
x = layers.Dense(64, activation='relu', name= 'intermediária_3')(x)
x = layers.Dense(64, activation='relu', name= 'intermediária_4')(x)
output = layers.Dense(10, activation='softmax', name= 'predictions')(x)

model = keras.Model(inputs=inputs, outputs=output)

In [4]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [5]:
x_train = x_train.reshape(60000, 784).astype('float32') / 255
x_test = x_test.reshape(10000, 784).astype('float32') / 255
y_train = y_train.astype('float32')
y_test = y_test.astype('float32')

x_val = x_train[-10000:]
y_val = y_train[-10000:]
x_train = x_train[:-10000]
y_train = y_train[:-10000]

In [10]:
model.compile(
	optimizer=keras.optimizers.RMSprop(),
	loss=keras.losses.SparseCategoricalCrossentropy(),
	metrics=[keras.metrics.SparseCategoricalAccuracy()],
)



In [11]:
history = model.fit(
	x_train,
	y_train,
	batch_size=64,
	epochs=2,
	validation_data=(x_val, y_val),
)


Epoch 1/2


ValueError: Exception encountered when calling Functional.call().

'intermediária_1' is not a valid scope name. A scope name has to match the following pattern: ^[A-Za-z0-9_.\\/>-]*$

Arguments received by Functional.call():
  • inputs=tf.Tensor(shape=(None, 784), dtype=float32)
  • training=True
  • mask=None
  • kwargs=<class 'inspect._empty'>